#!/bin/sh
# postinst script

set -e

case "$1" in
    configure)
        if which glib-compile-schemas >/dev/null 2>&1
        then
            glib-compile-schemas /usr/share/glib-2.0/schemas
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    triggered)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
